- hosts: webservers
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: 
        - nginx
        - postgresql
        - redis-server
        - python3
        - python3-pip
        - python3-psycopg2
      state: latest
      update_cache: yes
    become: yes
  
  - name: Ensure nginx is running
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    become: yes
  
  - name: Update nginx conf
    ansible.builtin.template:
      src: nginx.conf
      dest: "{{nginx_conf_path}}"
    become: yes
    notify: 
      - restart nginx
  
  - name: Change the index.html template
    ansible.builtin.template:
      src: index.html
      dest: "{{nginx_shared_path}}index.html" 
      force: yes
    become: yes
    notify: 
      - restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes
  